### ISSUE TITLE
SETNX with QueuedOnceTask has no effect

### ISSUE THREAD

**Issue by frewsxcv** [educreations/celery-queued-once#7]
http://redis.io/commands/setnx

We correctly use SETNX, but we need to check the return value of the Redis command. If it returns 0 (or None?) we shouldn't execute the task.

**Comment by frewsxcv** [comment]
So modifying the code to just use SETNX and check the value isn't that difficult of a task. An issue arises though: what do we return/throw if SETNX fails? Throwing exceptions is inconvenient and returning None is nonstandard. One solution to this is to [use pipelines](https://github.com/andymccurdy/redis-py#pipelines) and atomically call `SETNX` *and* `GET` so we also get the task ID in order to return it. I tried doing this but couldn't seem to get it working. I'm going to halt work on this for now.

**Comment by meastman** [comment]
I would probably just wrap [this section](https://github.com/educreations/celery-queued-once/blob/63986f3d448e8db33542b9a78a9295618d9b20a8/queued_once/task.py#L89-L105) in a loop and break out once either `_get_lock` finds another task or `_take_lock` succeeds. If `SETNX` fails, there's a really good chance that the next call to `_get_lock` will find another task; if it fails, then there's a really really good chance that the next call to `_take_lock` will succeed. For this particular case, it's probably not worth the hassle of using pipelines, since it would require much more redis-specific code.

**Comment by streeter** [comment]
I agree with @meastman. Creating a spin-lock should be fine. You could have a max-spins, in which case you would have to figure out what to do. It seems reasonable to create an exception for the library that gets thrown saying the task could not be registered. If someone is using this library, they are doing so because they only want a single version of a task getting registered, and that seems like an ok place to warn them.
